### ISSUE TITLE
[4s] TFPROBE shield against parasit light (from enviroment or direct sun light) 

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#103]
Po posledním testu se ukázalo, že aktuální uspořádání rotorové hlavy je stále velmi citlivé na mezeru mezi kloboučkm a senzorem TFPROBE. Řešením by bylo ve spodním dílu rotorové hlavy (888_1012) udělat kruhový rantl (cca 3 mm vysoký) který by tomuto světlu zabránil. 

![20210514_135146~2](https://user-images.githubusercontent.com/5196729/118267110-d6c43900-b4bb-11eb-8d53-b045f8cb9eca.jpg)

> Je to pouze rychlé řešení tohoto problému. Komletní řešení by mělo zároveň obsahovat úpravu TFPROBE aby IR signál byl minimálně modulovaný.

**Comment by kaklik** [comment]
Já myslím že jsem to už vyřešil [tímhle commitem](https://github.com/ThunderFly-aerospace/TF-G2/commit/b1ed02f40eaf48e77a5badfcbb5dcf91b27b6262#diff-027be5cde553524c3e09e1c626813e0c32ad6d9f485f891ab9735c5bd35d6f84) včera.  ;)  

Teď je to potřeba vyzkoušet.

**Comment by kaklik** [comment]
Tady je to složené

![image](https://user-images.githubusercontent.com/1194177/118408287-3cafec80-b685-11eb-95e7-0fe53d9de1d7.png)

![image](https://user-images.githubusercontent.com/1194177/118408299-49ccdb80-b685-11eb-80d0-09251f7461d8.png)


Nedokonalostí zatím je kvalita tisku mostu, který je ze spodní strany, lemu, který blokuje světlo.   Zadrhává se o něj hřebínek, tohle místo se zatím po tisku musí vyhladit pájkou nebo pilníkem.  Bude asi potřeba zvětšit toleranci pro tisk (asi nejlepší řešení). 

Zatím se mi ale nepodařilo najit takové světelné podmínky za kterých by to bylo rozbité. :)

**Comment by kaklik** [comment]
Při testovacím letu upravené řešení TFPROBE měřilo dobře.
