### ISSUE TITLE
Change of actuators (servos) in rotor-head and in rudder

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#105]
Nově se budou používat serva [BMS-115HV](https://www.blue-bird-model.com/products_detail/55.htm). Primárním důvodm je, že je potřeba posunout servo na rotorové hlavě trochu dopředu a usnadnit montáž. To aktuálně nelze realizovat z důvodu, že by bylo nutné tisknout vodorovný převis. (nyní se to tiskne na podložku) 

Stejné servo by se pak použilo do ocasu. Kde se to také zjednoduší. Připevňení serv by v obou případech bylo pomocí samořezných šroubků. 

- [x] Úprava rotorové hlavy 4S
- [ ] Úprava ocasu
- [X] úprava pylonu pro master verzi.

**Comment by roman-dvorak** [comment]
Ve větvi 4s je tato úprava už implementována. Jen otvor na samořezný šroub je zřejmě moc velký.

**Comment by kaklik** [comment]
> Ve větvi 4s je tato úprava už implementována. Jen otvor na samořezný šroub je zřejmě moc velký.

A myslíš tím, že jsou implementovány všechny body zmíněné výše?  Protože ani jeden z nich nevidím zaškrtnutý, což je trochu matoucí.

**Comment by roman-dvorak** [comment]
Ocas není implementovaný vůbec. A 4S rotorová hlava má zmíněný nedodělek.

**Comment by kaklik** [comment]
> Ocas není implementovaný vůbec. A 4S rotorová hlava má zmíněný nedodělek.

Ok, a co znamená ten bod "úprava pylonu pro master verzi." ?

**Comment by roman-dvorak** [comment]
asi to znamená se rozhodnout, která serva se pro master verzi budou používat. Pokud tyto s příčnou montáží (BMS-115HV) tak snížit ten sloupek pro přišroubování a změnit směr díry, kterou se šroubují za přírubu serva. 

Tyto pylony už jsou nemergeovatelné.

**Comment by roman-dvorak** [comment]
> Ve větvi 4s je tato úprava už implementována. Jen otvor na samořezný šroub je zřejmě moc velký.

Opraveno.

**Comment by roman-dvorak** [comment]
Vypadá to, že u ocasních ploch bude provedeno více úprav. Aktuálně úprava ocasu pro připevnění serva nemá moc význam. Na pár dalších kusech lze řešit tavným lepidlem. 

Umístění serva na rotorové hlavě bylo několika lety otestováno a vypadá jako dobré.

**Comment by kaklik** [comment]
Já bych tu úpravu ocasu pro lepší montáž serva docela rád viděl implementovanou.. To tavné lepidlo se mi nezdá jako moc dobré řešení, měli bychom se totiž už blížit k nějakému velmi definovanému způsobu montáže. 
Také bych rád, aby ocasní servo bylo lépe kryto při nárazu ocasu do země, aby to nebyl první díl o který se vírník zasekne.
