### ISSUE TITLE
ThunderMill - Generation of Kicad edge layer from OpenSCAD

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#114]
Aby bylo možné vyrobit desku, která bude vycházet z OpenSCAD návrhu, je potřeba dodržet následující postup. Je potřeba, abyste se @ChroustJan a @Alsa-Tucnak dohodli, kde kterou část udělá. Já bych navrhoval, aby @Alsa-Tucnak  končila vygenerováním SVG stop. 

# Kroky: 

- [x] Namodelování prototypu v OpenSCADU - @Alsa-Tucnak 
- [x] Otestování vytištěných disků (sestavení) - @Alsa-Tucnak 
- [x] Export dat pro import do kicadu - Frézování  - @Alsa-Tucnak 
- [x] Export dat pro import do kicadu - Měděná vrstva  - @Alsa-Tucnak 
- [x] Export dat pro import do kicadu - Vrtané otvory - @Alsa-Tucnak 
- [x] Import všech dílčích dat do Kicadu - @ChroustJan 
- [x] Dokončení PCB (schéma, layout) - @ChroustJan 

**Při všech importech do kicadu je potřeba importovat na určité souřadnice (screenshoty toto pravidlo nereflektují)**

### Namodelování v OpenSCADu

![obrazek](https://user-images.githubusercontent.com/5196729/126719497-1f24ce39-e456-4ee4-aa27-336a5fa49408.png)

Vytvoření řezu
![obrazek](https://user-images.githubusercontent.com/5196729/126719511-213cf3be-4d4b-4f86-9b0d-d562e3782d14.png)

Uložit jako svg:
Soubor -> Exportovat -> Exportovat jako SVG

Postup je potřeba opakovat pro všechny vrstvy. Tj. Obrys, měď, atd.. 

### Import do KiCADu

Otevřít Kicad - PCBnew
Vybrat ořezovou vrstvu
Soubor -> Import -> Grafika

![obrazek](https://user-images.githubusercontent.com/5196729/126744893-b682c5c2-aaef-4216-a5aa-44706a76ce08.png)

Zde je potřeba vybrat správný soubor, Vybrat vrstvu pro frézavání (edge.Cuts), měřítka 1,0. Ideální je umístit SVG na určité souřadnice výkresu. Protože na stejné souřadnice se budou vkládat další modely.

Následně disk umístit do prostoru

V 3D náhledu bychom měli vidět toto:
![obrazek](https://user-images.githubusercontent.com/5196729/126719723-a85df5d2-ea8c-4bac-928f-b10b55d3b41b.png)

Pokud bude potřeba definovat i plochu výplně, tak to se musí vytvořit vlastní openscad modul obsahujíci plochu měděné výplně˙
![obrazek](https://user-images.githubusercontent.com/5196729/126719917-e86689c0-f881-4248-8157-27b14fdf1d48.png)

![obrazek](https://user-images.githubusercontent.com/5196729/126720015-e1a9a97f-f75f-495e-aa78-296949e7c2d6.png)

![obrazek](https://user-images.githubusercontent.com/5196729/126720033-8750ab2c-0e75-4643-a17c-48af29ba20b2.png)

A tento objekt se chová jako měděná výplň. To se může hodit na přesné namodelování prostorů elektrod. 

Otvory pro vrtání
Nevím o přímé cestě, jak vložit do kicadu otvorp pro vrtání. Je tedy nutné si pomoct tak, že v OpenSCADu se vygeneruji pomocné značky pro místa vrtání. To se naimportuje do kicadu, do nějaké uživatelské vrstvy. A v Kicadu se na tato místa vloží vrtané díry. 

![obrazek](https://user-images.githubusercontent.com/5196729/126747073-c2aff6a4-436d-4ed2-841c-d3ec3adf7ea0.png)
![obrazek](https://user-images.githubusercontent.com/5196729/126747176-ca0de40e-3f94-41dd-a0e8-a19a5e2827d5.png)

V kicadu následně umístit díry jako footprint:
![obrazek](https://user-images.githubusercontent.com/5196729/126747409-2afc1466-162f-4f52-abd8-a4e1a4efa104.png)

**Comment by kaklik** [comment]
[Zde jsem našel pána na youtube](https://youtu.be/hHURDpH471o?t=194), který má trik na to, jak díry v DXF zarovnat s footprinty děr tak, aby se ten střed nemusel hledat ručně.

**Comment by kaklik** [comment]
Issue přesunuto sem: https://github.com/UniversalScientificTechnologies/THUNDERMILL01/issues/5 Aby jej bylo možné zařadit do projektu.
