### ISSUE TITLE
Lightweight motor holder

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#132]
![image](https://github.com/ThunderFly-aerospace/TF-G2/assets/1194177/b5ca59f7-a04b-422b-b91b-da3d69b28640)

3D tištěný držák motoru by se zřejmě dal výrazně odlehčit.  Navrhoval bych do něj udělat díry, které by zároveň snížily spotřebu plastu na jeho vytištění. Aktuálně je potřeba držák vyměnit na obou havarovaných vírnících. 
Hmotnost současného držáku je ~40g.

Možná že lze odebrat i celou středovou část, která spojuje díry pro šrouby motoru. Je s tím akorát potíž, že bude obtížné takový tvar vytisknout.

**Comment by roman-dvorak** [comment]
Já jsem o tomhle také přemýšlel. A ještě mne napadlo, že by se mohl využít duralový kříž, který je s motorem dodáván. Sice to přidá další tři šrouby ale ve výsledku by to mohlo být ještě lehčí.

**Comment by kaklik** [comment]
Současné upravené řešení je dostatečné.
