### ISSUE TITLE
Úprava horní části pylonu

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#15]
- [x] Zvětšit výšku otvoru pro servo .
---
 - [x] Zvednout držák serva, protože nyní koliduje s rámečkem pro airspeed senzor. 
 - [x] Změnit velikost děr pro přišroubování serva

**Comment by kaklik** [comment]
Tohle mi přijde jako vyřešené.

**Comment by roman-dvorak** [comment]
Issue jsem zaktualizoval.

**Comment by roman-dvorak** [comment]
Otvor na servo zvetšen. A zároveň provedeno odlehčení dílu
