### ISSUE TITLE
Pokusit se o implementaci RPM senzoru

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#17]
Tohle by se mohlo vyřešit tak, že se sloupek s ložisky sníží o cca 5 mm a nasadí se na to taková obrácená mistička, která se bude otáčet s rotorem. Ve spodní části pak bude nějaký senzor.

Zde je otázka, jaký senzor to bude??  
 * IR reflexní
 * IR brána
 * Hallova sonda

**Comment by kaklik** [comment]
To je stejný problém jako tohle: https://github.com/ThunderFly-aerospace/force_balance/issues/7

**Comment by kaklik** [comment]
Implementována IR brána.
