### ISSUE TITLE
Dokončit docs.px4 stránku pro Auto-G2

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#18]
Cílem je naučit se, jak s touto dokumentací zacházet. Jaké bude mít komunita požadavky atd..

Text je rozepsán zde: https://docs.google.com/document/d/1p8QPR6BAmqDs6eTo3oPDJKxsFIAMStuHuRvq7hzDEPY/edit?fbclid=IwAR0um9o1BWj3zY5KZpIYuSvzSpZiG_S9OVbog_OKz805KD17tEJQtICigdU#

Je to text pro tuto stránku: https://docs.px4.io/master/en/airframes/

**Comment by kaklik** [comment]
Tohle je duplicitní k: https://github.com/ThunderFly-aerospace/Auto-G2/issues/24

**Comment by kaklik** [comment]
Synchronizoval jsem text dokumentu s markdownem v dokumentaci. Přidal jsem i odkazy pro některé tišné díly. Nyní je potřeba vložit obrázky a nějaké úplně základní video.

**Comment by kaklik** [comment]
Rozsah by zřejmě měl být obdobný této stránce: https://docs.px4.io/master/en/frames_vtol/vtol_tailsitter_caipiroshka_pixracer.html

**Comment by kaklik** [comment]
Vytvořen pull-request: https://github.com/PX4/px4_user_guide/pull/819

**Comment by kaklik** [comment]
Pull-request zamegován a dokumentace je k dispozici na: https://docs.px4.io/master/en/frames_autogyro/thunderfly_auto_g2.html
