### ISSUE TITLE
Nosná podložka

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#2]
K dovyřešení:
- [ ] Vyřešit způsob připevnění předního podvozku. 
---
 - [X] Základní návrh (done by @zelenac)
 - [X] Úprava rozměrů a prvotní vytvoření odlehčovacích otvrů (done by @roman-dvorak)
 - [x] Optimalizace hmotnosti: Chytřejší otvory pro odlehčení
 - [x] Místo na připevnění podvozku
 - [x] Zapuštění matek v postranním rantlu. 
 - [X] Rozšířit podložku o 10 mm (celková šířka 70 mm), @roman-dvorak 
 - [x] Chybí díra pro přišroubování držáku motoru do podložky. 
---

Nosná podložka malého vírníku se bude skládat ze dvou identických částí. 

Budou to 2 destičky, které se následně vzájemně sešroubují ~pomocí nějaké vytištěné spojky~. 
Destička bude mít podélně vyšší límec, který bude mít dva úkoly. Zpevnění celé konstrukce. Vytvoření míst pro připevnění bočních stěn. 

~Podložka bude 55 mm široká a dlouhá 2x140 mm~ (staré údaje). Tato délka byla zvolena z technologických důvodů - maximální tiskový rozměr.

![20190831_165358](https://user-images.githubusercontent.com/5196729/64066277-e16f6980-cc17-11e9-97fc-b69292336f6a.jpg)

Příčný řez dílem
![20190831_165404](https://user-images.githubusercontent.com/5196729/64066258-9c4b3780-cc17-11e9-908b-f277ae0a8cea.jpg)

Ve spodní části budou díry na šrouby na připevnění dalšího příslušenství. Budou zarovnané do nějaké určité mříže. Předpokládám nějakých 4-5 řad. Budou to díly na M3 šrouby.

Všechny rozměry musí být udělány pomocí proměnných parametricky.

**Comment by roman-dvorak** [comment]
Nosná podložka je aktuálně ve stavu, že obsahuje boční lem s řadou děr pro připevnění bočnic. Podložka bude dělena na 2 časti. Na obrázku to je naznačeno. Bočnice budou na 3 časti a je potřeba zajistit, aby předěl částí nevycházel na stejné místo. 

Od původního modelu došlo k odlehčení vytvořením vetších otvorů ve dnu modelu. Tyto otvory bude potřeba upravit v návaznosti na připevnění podvozku. Může pak být provedeno další odlehčení. Nebo ztečení či chytřejší vyztužení. 

Na začátek první zprávy jsem vypsat věci k úpravě. 

![Snímek z 2020-04-02 23-15-01](https://user-images.githubusercontent.com/5196729/78300816-674ded00-7538-11ea-9fb6-8127f7f4241d.png)

**Comment by roman-dvorak** [comment]
Do podložky přidány šestihrany na zapuštění matky, upraveno odlehčení a otvory pro připevňení ocasu a předního podvozku.

**Comment by kaklik** [comment]
Ten způsob připevnění předního podvozku na dva šrouby je podle mě vyhovující.
