### ISSUE TITLE
Thingiverse

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#22]
Vyexportovat STL na thingiverse, připravit popisné texty s odkazy na návody atd.. Přidat obrázky (reálné fotky, video, ..)

**Comment by kaklik** [comment]
Thingivese už asi není v kurzu, nyní se používá https://www.prusaprinters.org/prints

**Comment by kaklik** [comment]
Tohle se asi bude dost špatně realizovat vzhledem ke způsobu slicování modelů...

**Comment by roman-dvorak** [comment]
Aktuálně mi toto issue připadá nerelevantní..
