### ISSUE TITLE
Odlehčit boční stěny

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#36]
Boční stěny by jednak mohly obsahovat více neortogonálních otvorů s diagonálními příčkami. (Aby sily byly přenášeny přes staticky určité trojúhelníky)

Taktéž je vhodné, aby boční stěny měly v řezu tvar U nebo H.  To znamená, že materiál nebude obsahovat spodní a vrchní vrstvu a mezi tím výplň, ale pouze jednu plošnou vrstvu.

**Comment by kaklik** [comment]
To odlehčení stěn by zřejmě šlo udělat tak, že se od plného modelu odečte tvar, který se vytvoří transformací [offset](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#offset) z plošného objektu před tím, než se do něj nadělají díry pro šrouby.
