### ISSUE TITLE
Výběr barevné kombinace komponent vírníku

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#38]
Pro zlepšení estetické kvality designu je nutné, aby vírník měl vhodnou barevnou kombinaci.  Z technických důvodů je vhodné, aby počet barev byl co nejnižší. 

Kvůli zajištění viditelnosti je vhodné, aby baravená kombinace zahrnovala světlou (viditelná proti tmavému pozadí) a tmavou barvu (viditelná proti obloze). 

Barevná kombinace by měla vycházet z grafického manuálu TF.  

Tento úkol je zřejmě vhodné začít řešit až po jiných konstrukčních úpravách, jako je:

- #15
- #16
- #9

**Comment by kaklik** [comment]
Použitelné barevné vzorky jsou tyto: 

![image](https://user-images.githubusercontent.com/1194177/83388605-04b98600-a3ef-11ea-8f2b-730172aeff61.png)

**Comment by roman-dvorak** [comment]
Zřejmě to stačí udělat na tomto připraveném modelu:
https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/blender/TF-G2.blend

ze kterého vznikl například tento obrázek
![TF-G2](https://github.com/ThunderFly-aerospace/TF-G2/raw/master/CAD/render_Img/TF-G2_004.png)

**Comment by roman-dvorak** [comment]
Po diskuzi s @ChroustJan a @kaklik to vypadá, že bude potřeba mít 2 verze. Jednu hezkou, která bude možná v TF barvách (konkrétní odstín oranžové) a druhou, která bude optimalizovaná pro nejlepší viditelnost na obloze.

**Comment by roman-dvorak** [comment]
Ukázky:

![Snímek z 2020-06-18 15-10-44](https://user-images.githubusercontent.com/5196729/85041810-b6e0a400-b18a-11ea-98e8-6bae9a39e6fa.png)

![Snímek z 2020-06-18 15-39-13](https://user-images.githubusercontent.com/5196729/85041820-b9db9480-b18a-11ea-8f51-7681e30bcf07.png)

![Snímek z 2020-06-18 15-49-09](https://user-images.githubusercontent.com/5196729/85041830-bd6f1b80-b18a-11ea-8383-3435ad537704.png)
![Snímek z 2020-06-18 16-01-22](https://user-images.githubusercontent.com/5196729/85041841-c102a280-b18a-11ea-8889-8d5856634f0e.png)

**Comment by roman-dvorak** [comment]
@fluktuacia navrhla následující barevnou kombinaci. Konstrukční prvky (tj. spodní podložka, příhradové bočnice, polička GPS, polička akumulátoru, přepážka motoru, pylon kompletně, rotorová hlava a pohyblivá část směrovky budou šedé. 

Ostatní části (okrytování, výškovka, směrovka a rotor) budou mít nějakou jednu barvu. Primárně se uvažuje o modré. Ale je možné jakoukoliv jinou. To bude podle požadavků zákazníka nebo letových podmínek. 

Konce rotoru by měly být nabarvené barvou, která je kontrastní ke zbytku. To především ke zvýšení bezpečnosti. A zároveň to vytváří docela zajímavý efekt. 

![106572625_1184218965248576_8162224110455168221_n](https://user-images.githubusercontent.com/5196729/86493942-c14a9280-bd73-11ea-8d9d-9e6010871457.png)

**Comment by kaklik** [comment]
Konce rotoru nabarvené barvou?  Nemělo by to spíše být rovnou vytištěné z jiné barvy?

**Comment by roman-dvorak** [comment]
Jo. Ano vytištěné. ale z jiné barvy prostě.
