### ISSUE TITLE
Vykreslování naměřených dat do mapových podkladů

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#42]
Pro některé druhy měření by bylo vhodné umět vykreslovat naměřené skalární hodnoty do mapy, tak aby bylo možné vytvořit 3D heatmapu měřené veličiny v závislosti na poloze.  Vykreslovat tato data by mělo být možné online (real-time) v průběhu letu tak i z logů v post processingu. 

Real-time vykreslování lze použít pro kontrolu průběhu měření ale především pro následnou navigaci do zajímavého místa popřípadě jeho detailnějšího prozkoumání. 

Není asi vhodné pro tento účel vytvářet vlastní SW, protože je to velmi komplexní problém. Bylo by tedy vhodné využít nějakého existujícího mapového frameworku, který s takovými daty umí zacházet. 

Hlavní požadavky které máme jsou: 

1. Vizuální atraktivita zobrazení (bude využíváno i pro marketingové prezentace)
2. Možnost připojení na realtime data  (MavLink, ROS/MAVROS,MQTT, ...).
3. Zobrazení bodových dat a jejich interpolace přes prostor (Inverse Distance Weighting (IDW))

Známé programy:
 * [OpenDronMap](https://www.opendronemap.org/)
 * [QGIS](https://qgis.org/en/site/about/index.html)
 * [NGV](http://ngv.norut.no/)
 * [Marble](https://marble.kde.org/)
 * [Kepler](https://kepler.gl)
 * [ArcGIS](https://cs.wikipedia.org/wiki/ArcGIS)
 * [STK12](https://www.agi.com/newstk) - komerční nástroj, který asi využívá NASA. 
 * [Cesium](https://cesium.com/blog/industries/uav/)
 * FlightGear? 
 * [ROS](https://www.youtube.com/watch?v=BDzufMACM2M)? 
 * [ParaView](https://www.paraview.org/)

Ještě by bylo zajímavé projít [tento seznam](https://www.osgeo.org/projects) a podívat se, zda tam není něco vhodného. Zajímavě vypadá například [GrassGis](https://www.osgeo.org/projects/grass-gis/).

Vizualizační knihovny
 * [VisPy](http://vispy.org/)

Komerční řešení podobné problematiky
 * https://www.iatecps.com/soarability

Pro inspiraci:
 * [Vizualizace mraků](https://vimeo.com/156297434) - zřejmě pomocí nástroje [ParaView](https://www.paraview.org/)

**Comment by kaklik** [comment]
Jako nejperspektivnější řešení se zatím jeví přihnutí některého z existujících příkladů nástroje Cesium:

- https://cesium.com/blog/2019/04/29/gpu-powered-wind/
- https://cesium.com/blog/2017/11/17/paragliding-logbook/ 
- https://cesium.com/blog/2018/05/08/activeflight/
- https://cesium.com/blog/2016/02/03/vega/

Části software které pro realizaci něčeho takového v Cesiu jsou potřeba: 

- Datová pumpa z MavLink packetů
- Databáze pro dočasné uložení dat  (z ní se budou data zobrazovat a v případě webového prohlížení i obnovovat)
- Definice zobrazení a výpočet interpolovaných dat
