### ISSUE TITLE
Bandáž pro akumulátory

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#46]
Už opakovaně se stalo, že akumulátor byl poškozen o šroub na motorové přepážce. Je tak zřejmé, že toto místo bude vyžadovat konstrukční úpravu. Možnosti jsou:

- Zapustit šrouby do motorové přepážky
- na akumulátory vytvořit ohrádku, která bude akumulátor chránit před kontaktem se šroubem. 

Osobně bych asi preferoval nějakou formu zapuštění šroubů, nebo vytvoření krytu na tyto šrouby.  
Ohrákda na akumulátor totiž způsobí komplikace, při změnách akumulátoru za různé typy.

**Comment by roman-dvorak** [comment]
Zapuštění šroubu je v tomto dílu problematické, motor za tyto šrouby tahá. Takže aktuálně tahá přes celý průřez dílu přes vrstvy, což je optimální řešení.

Navrhoval bych vytvořit nějakou krytku, která by se přišroubovala pod hlavy šroubů. a vytvářela by právě to zapuštění.  Zároveň by to mohla být krytka koukající osy od motoru.

**Comment by kaklik** [comment]
A není potřeba se té přečnívající osy z motoru spíš zbavit?  Protože takhle překáží i akumulátorům.

**Comment by roman-dvorak** [comment]
Určitě by to bylo lepší :)

**Comment by kaklik** [comment]
Zatím vyřešeno zapuštěním šroubů.
