### ISSUE TITLE
Asistované odpojení z platformy

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#56]
Ve vírníku by měl být asistent odpojení z [Tesengiry platformy](https://github.com/ThunderFly-aerospace/TensegrityPlatform), který při dosažení určitých letových otáček rotoru odpojí vírník od platformy. Takové odpojení může být povoleno na základě například stisknutím tlačítka na RC vysílače.

To vyřeší problém latence mavlink přenosu a odpojení v optimálních otáčkách rotoru aby nebyl moc přetočený.

**Comment by kaklik** [comment]
Aktuální implementace asistovaného odpojovače funguje.
