### ISSUE TITLE
Úprava rotorových podložek

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#60]
Rotorové podložky je potřeba upravit tak, aby obrysem seděly k nové rotorové placce #57. 

Díly [888_4005](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/stl/888_4005.stl), [888_4004](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/stl/888_4004.stl)  a [888_4006](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/stl/888_4006.stl) je potřeba tak, aby lícovaly ze spodní i horní strany s novou rotorovou destičkou [888_4002](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/stl/888_4002.stl)
Cílem tak je, aby rotorová destička byla sevřena mezi ostatní díly v celé svojí ploše. 

Aktuální nekompatibilita je vidět na následujících dvou obrázcích ze sestavy [888_4101](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/src/drawings/888_4101.scad) 

![image](https://user-images.githubusercontent.com/1194177/87679198-2cd12e80-c77c-11ea-81cd-0ba14d1968ae.png)

![image](https://user-images.githubusercontent.com/1194177/87679351-5c803680-c77c-11ea-9384-75cad8897e6c.png)

**Comment by cesilko1** [comment]
![888_4101](https://user-images.githubusercontent.com/31468660/87714281-d7147a80-c7ab-11ea-902e-5f31bcc99079.png)

**Comment by kaklik** [comment]
Momentálně je tohle issue vyřešeno dočasně tím že podložky jsou stále tvořeny polygonem, který ale v důsledku zřejmě není parametrický.  

To znamená, že například nelze: 

- Nastavit mezeru v podložkách pro konkrétní úhel prověšení listů před startem
- Rozteče šroubů a pozice jsou pravděpodobně momentálně dány číselnými hodnotami v kódu, těžko se tak díly provazují vzájemně, nebo vytváří závislosti na dalších rozměrech.

**Comment by kaklik** [comment]
Tohle bych zatím navrhoval neřešit a počkat jak dopadne free-flapping-rotor od @slimonslimon

**Comment by kaklik** [comment]
Výsledkem úspěšného testu free-flapping rotoru je, že není potřeba tento úkol dále řešit.
