### ISSUE TITLE
Pohonné ústojí vírníku

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#65]
Pro opakovatelnost výroby vírníků TF-G2 (TF-G3) je potřeba vybrat spolehlivé a dostupné ESC regulátory, motory a vrtule. 

#  ESC 

- [x] Vybrané ESC:

Na regulátory jsou požadavky
 * Telemtrická data přes UAVCAN
 * Dostupnost
 * Výkon ~50A (@ 3S) 
 * OpenSource (výhoda, pokud ne tak reálná měření)
 * 

## [Myxa](https://zubax.com/products/myxa)
Regulátor Myxa od Zubaxu. 

Klady
* Odpovídající výkon
* UAVCAN (plná podpora včetně nastavování přes CAN) 
* Malý rozměr, malá hmotnost
* Zubax vypadá jako docela komunikující firma, aktivní vývoj
* OpenSource, několik variant
* Podpora PPM + UAVCAN ovládání

Zápory
* Vyžaduje 4S akmumulátor
* Nemá BEC

# Motor
- [x] Vybraný motor: 

Požadavky:
 * 

# Vrtule
- [ ] Vybraná vrtule: 

Požadavky:
 * Známé parametry
 * Dostupnost
 * Cena (spotřební materiál)

Jako součást s nejmenší možností výběru je je asi regulátor. Při volbě Myxi jsme omezeni především na to, že nejnižší podporované napětí splňuje 4S akmululátor. Od toho se odvíjí výběr zbylých komponent.

**Comment by roman-dvorak** [comment]
Po několika pokusech se ukazuje, že MYXA pro TF-G2 (4S) dostačuje ale s nevelkou výkonostni rezervou.

Stále tedy v úvahu připadá používání VESC regulátoru. Na motorové váze bude vhodné tyto dva regulátory porovnat a případně se pokusit myxu nějakým způsobem lépe nastavit.

**Comment by kaklik** [comment]
Nevím sice na jakém konektoru je u [nového VESC](https://www.neven.cz/kategorie/elektronicke-soucastky/stmivace/pwm-regulator-otacek/regulator-vesc-bldc-superfoc6-8-50a-esc/) RC PWM vstup. Nicméně jsem zjistil, že zřejmě nemáme sedmipinový konektor.  Není tak možné jeden z konektorů na PCB použít. Konektory, ke kterým máme protikusy jsou vyfoceny na následujícím obrázku. 

![image](https://user-images.githubusercontent.com/1194177/124576135-50d5c600-de4c-11eb-8441-61e457c887ca.png)

**Comment by kaklik** [comment]
Tohle issue je zřejmě potřeba rozebrat na dílčí části, které je nutné řešit samostatně.
