### ISSUE TITLE
Lámací rotorová hlava

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#69]
V některých případech se stává, že se z rotorové hlavy oddělí pouze jeden list. Buď je ho předchozím poškozením, nebo nárazem při havárii. 
Důsledkem pak je utržení celého pylonu druhým nepoškozeným listem.  Trhací podložky tomuto stavu nedovedou zabránit, neboť jsou konstruovány tak, aby v tahu přenesly relativně velkou sílu a ke svému zlomení potřebují moment protilehlého listu. 

Řešením by mohla být úprava ložiskového domku rotorové hlavy tak, aby došlo při extenzivní boční síle k odlomení celého šroubu rotoru i s ložisky. V běžném režimu je zde boční síla téměř nulová, až na vibrace a anomální letové stavy. Při odlomení jednoho z listů boční síla radikálně vzroste.

**Comment by roman-dvorak** [comment]
V #64 @kaklik navrhl následující řešení:

> Co se týká řešení té lámací hlavy, tak jsem přemýšlel o rozdělení tohoto dilu na dva díly, které by se šroubovaly k sobě. Tím by se po odlomení teoretecky nemusela odšroubovávat táhla k servům.

**Comment by roman-dvorak** [comment]
@Alsa-Tucnak Je nějaký pokrok s touto věcí? 
v jaké větvi je to plánované namodelovat?

**Comment by kaklik** [comment]
![image](https://user-images.githubusercontent.com/1194177/118356229-793ff300-b574-11eb-893f-c29cd9fbe16f.png)

Takhle od oka je ta drážka přibližně dobře, měla by být 4mm pod přepážkou.  Protože ložisko je horní stranou doraženo na zub, který vytváří přepážka (ta se po tisku odvrtá) a samotné ložisko [623 SKF](https://www.skf.com/group/products/rolling-bearings/ball-bearings/deep-groove-ball-bearings/productid-623-2Z) je  4mm vysoké. 

Podstatným zlepšením by ale bylo, kdyby ulamovací díl byl vyměnitelný a šrouboval se k základně s táhly k servům.

**Comment by kaklik** [comment]
@Alsa-Tucnak  nyní rozdělila rotorovou hlavu na dva díly 

![image](https://user-images.githubusercontent.com/1194177/122202832-b3ffb880-ce9d-11eb-85c3-212dd4c23344.png)


![image](https://user-images.githubusercontent.com/1194177/122203064-f4f7cd00-ce9d-11eb-966f-6df5b6d487b5.png)

Myslím že řešení je docela dobré.

 - [ ] šestihran na matice šroubů pro uchycení sloupku s ložisky musí být na spodní straně základny. To znamená viditelný z tohoto pohledu:

![image](https://user-images.githubusercontent.com/1194177/122203343-3b4d2c00-ce9e-11eb-8687-28af88202fbd.png)

**Comment by roman-dvorak** [comment]
Po pokusu o sestavení kompletní rotorové hlavy s novým trhacím ložiskovým domkem jsme přišli na tyto problémy: 
Sloupky pro mlýnek byly uříznuté.

- [ ] kostka, ve které jsou svislé šrouby pro odmontování trhací části, zasahuje do rolničky, kterou díky tomu nelze hladce otáčet.  
![20210624_162836](https://user-images.githubusercontent.com/5196729/123410692-e2714800-d5af-11eb-9429-eba0e80523bb.jpg)

- [ ] Celý díl je nyní vyšší. Což se projevuje mezerou pod rolničkou. 
![20210624_162806](https://user-images.githubusercontent.com/5196729/123419252-4c8eea80-d5ba-11eb-85f1-cb93693ea587.jpg)

![20210624_162856](https://user-images.githubusercontent.com/5196729/123419304-5ca6ca00-d5ba-11eb-98c9-bc46c198031d.jpg)

Napadají mne dvě řešení:
 * Snížit sloupek, ve kterém jsou ložiska, do původního stavu. Ideálně tak, aby se zachovala původní rozteč ložisek. 
 * Pokud je nějaký vážný důvod zachovat tento zvětšený sloupek, tak je potřeba zachovat původní geometrii rotorové hlavy viz  následující obrázek. Původní rotorová hlava to splňuje. 

![pastedImagefile](https://user-images.githubusercontent.com/5196729/123420575-020e6d80-d5bc-11eb-8ad3-53d7fbb61b1a.png)

Z důvodu těchto problémů s touto hlavou nebyl proveden žadný letový pokus.

**Comment by kaklik** [comment]
Ještě sem doplním, že test zlomení vyměnitelného dílu dopadl dobře v tom smyslu, že se zlomil na místě, kde je zápich a síla potřebná ke zlomení mi přijde přibližně adekvátní zamýšlenému užití.

![image](https://user-images.githubusercontent.com/1194177/123505437-620a2000-d65f-11eb-9f61-679de6c96533.png)

**Comment by Alsa-Tucnak** [comment]
> 
>     * [ ]  Celý díl je nyní vyšší. Což se projevuje mezerou pod rolničkou.
> 
> Napadají mne dvě řešení:
> 
>     * Snížit sloupek, ve kterém jsou ložiska, do původního stavu. Ideálně tak, aby se zachovala původní rozteč ložisek.
> 
>     * Pokud je nějaký vážný důvod zachovat tento zvětšený sloupek, tak je potřeba zachovat původní geometrii rotorové hlavy viz  následující obrázek. Původní rotorová hlava to splňuje.
> 
> 
> Z důvodu těchto problémů s touto hlavou nebyl proveden žadný letový pokus.

Nevím, jak došlo ke zvýšení hlavního válce. Pokud je to opravdu vyšší, tak je to omylem. Ověřte prosím, že je to opravdu vyšší. Případné snížení nebude problém, jen podle modelu to má správnou výšku.

**Comment by roman-dvorak** [comment]
Výška nyní vypadá správná. Bohužel jsem včera zapomněl si odvézt nějakou složenou rotorovou hlavu, takže to neotestuji kompletně.

Ale má to problém, že šrouby, které stahují ty dva díly k sobě, kolidují s kódovacím diskem na rolničce. Nepůjde tak s rolničkou (rotorem) volně otáčet. 

Řešením by bylo posunout šrouby do osy rotoru. 

![20210723_132713_HDR.jpg](https://user-images.githubusercontent.com/5196729/126775931-3aefd286-077a-4cc0-a66a-ebe6a63f5629.jpg)

![20210723_133225.jpg](https://user-images.githubusercontent.com/5196729/126776012-a38f7276-f097-42e6-b0bc-c07483da516b.jpg)



Po vytištění má sloupek ze spodní strany nějak divně vytištěné mosty. Zřejmě je to způsobené kulatou dírou v horní straně. Bylo nutné to očistit. Jinak byl sloupek šikmo.

![20210723_125817.jpg](https://user-images.githubusercontent.com/5196729/126776096-ebea4f38-9ea7-4900-a3fe-73e55f0043eb.jpg)

**Comment by kaklik** [comment]
Aktuální řešení bylo ověřeno praktickým letem, jako funkční. :)
