### ISSUE TITLE
888_1007 a 888_1008, pylon

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#7]
- [x] Základní model
---
Pylon byl namodelován po vzoru modelu virníku Auto-G2. Jedná se tedy o 2 placky z boků vírníku sbíhající se do středu k rotorové hlavě. Každá část bude uprostřed sešroubována ke středovému rámečku. Vice v samostatném issue. 

Stěny pilonu budou umístěny šikmo. Proto je vhodné aby na koncích byly klíny. Na spodní časti je to už implementováno.

![Snímek z 2020-04-02 23-39-17](https://user-images.githubusercontent.com/5196729/78302503-2efbde00-753b-11ea-9f9c-cd099cb46e0b.png)

**Comment by roman-dvorak** [comment]
Aktuální návrh pilou vypadá takto:

![20200410_145200](https://user-images.githubusercontent.com/5196729/79025078-1451e680-7b85-11ea-8158-4c81c2f3d80b.jpg)

![20200410_145218](https://user-images.githubusercontent.com/5196729/79025081-187e0400-7b85-11ea-9b3c-e70556289578.jpg)

![20200410_145232](https://user-images.githubusercontent.com/5196729/79025087-1d42b800-7b85-11ea-9929-ff0af52d4242.jpg)

Pro první létací prototyp mi to přijde dostatečné.

**Comment by kaklik** [comment]
Má to nějakou použitelnou tuhost?

**Comment by roman-dvorak** [comment]
Horní část je dostatečně tuhá. U spodní jsem přemýšlel o nějaké příčce popřípadě přímodelování výztuhy. Ale to bych řešil později.

Spodní část nemůžu moc otestovat, protože nemám vytištěnou podložku ve správném rozměru. 

Jinak jsem nepsal. Celé (tak, jak je to na fotce) má 77g

Ještě jsem přemýšlel o posunutí osy rotoru trochu dopředu. Aby to bylo v ose pylonu a nevznikal tam takový moment, který by tomu pomáhal se kroutit. Ale to také až do další verze.

**Comment by roman-dvorak** [comment]
Jak je ta střední příčka, tak tam jsou připevňovací otvory pro Venturiho trubici.
