### ISSUE TITLE
Otočení osy serv

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#70]
Osu serv na pylonu je potřeba otočit po směru letu. 

 - [X] Otočení serv
 - [x] Rozšíření (hloubky) sloupku pro připevňení serva.
 - [x] Nepatrně zvetšit průměr otvoru pro samořezný šroub.
 - [x] Špatné otočení v printplatu - aktuálně to netvoří použitelný pár. Nová verze má o jednu osu symetrie méně.

**Comment by roman-dvorak** [comment]
Aktuální řešení vypadá takhle. K vyřešení tohoto isuue navrhuji 2 úpravy. 

 * Rozšíření (hloubky) sloupku pro připevňení serva. 
 * Nepatrně zvetšit průměr otvoru pro samořezný šroub. 

![20201124_175926](https://user-images.githubusercontent.com/5196729/100127961-eef9ba80-2e7f-11eb-9d2e-50a760815a71.jpg)
![20201124_175931](https://user-images.githubusercontent.com/5196729/100127970-f1f4ab00-2e7f-11eb-840e-ee01f74bb201.jpg)

**Comment by roman-dvorak** [comment]
![20201124_230203](https://user-images.githubusercontent.com/5196729/100157140-5cbadc00-2eaa-11eb-99ae-d670f875e985.jpg)

**Comment by kaklik** [comment]
Trochu jsem nečekal, že ta serva budou z vnitří strany pylonu..   Protože takhle ta táhla jsou pod docela odlišným úhlem než kolmo na osu pohybu.  Ale fungovat to asi bude.

**Comment by roman-dvorak** [comment]
Ony se na vnitřní stranu tisknou kapsy na matky. Z druhé strany se to takto  udělá těžko. 

Spíše je blbé, že ty páky dodávané se servy jsou na obě strany. Což znamená, ze se musí uříznout a po jejím připadném zlomení už není možnost tu páku pouze otočit.

**Comment by kaklik** [comment]
Kdyby ta serva, ale byla z venku, tak tenhle problém s pákami odpadá.  Kapsy na matky jsou myslím vytisknout i směrem k podložce. 

Případně jde myslím prohodit ten šedý a modrý díl tak, že kasy by byly v tom šedivém horizontálním dílu.

**Comment by roman-dvorak** [comment]
ten šedý díl tam tvoří věc, že horní a spodní čast pylonu mají trochu jiný úhel vůči sobě. Ten rámeček je taková přechodka mezi těmito úhly. 

Tahle skladba tehdy měla nějaké opodstatnění. Teď už nevím jaké přesně.

**Comment by roman-dvorak** [comment]
V tom případě by se asi chtělo zamyslet nad nějakým komplexnějšim předěláním pylonu.
