### ISSUE TITLE
Namontovat TFGPS01A do TF-G2

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#71]
Na místo současné GPS je potřeba namontovat [TFGPS01A](https://github.com/ThunderFly-aerospace/TFGPS01)

Je proto potřeba: 

- [x] Upravit [GPS držák](https://github.com/ThunderFly-aerospace/TF-G2/blob/master/CAD/src/888_1015.scad), tak aby obsahoval otvory pro šrouby na GPS.
- [x] Sehnat plastové distanční sloupky
- [x] Vyměnit díl s GPS na vírníku

**Comment by roman-dvorak** [comment]
S TFGPS01 byl úspěšně proveden první let. Na palubě byly paraelně dvě GPS. Je z nich vytvořen GPS_DUMP. 

Následující postup, po tomto issue, je zlepšit krabičku.
