### ISSUE TITLE
Namontovat TFPM01 Payload

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#73]
Na vírník je potřeba namontovat TFPM01A prachový snímač.  

Tento krok lze udělat až po dokončení #71 a dalších oprav vírníku. 

Senzor má být namontován do přední části mezi motorem a pylonem rotoru.

**Comment by roman-dvorak** [comment]
Nomontování proběhlo vložením senzoru dovnitř konstrukce. Mezi ESC a autopilota. MLAB labduino je umístěno nad tím (mezi mezi spodní častí pilonu a proti vyklepání je to pojištěno stahovací páskou se suchým zipem. 

Senzor je trigrován z GPS PPS signálu.
