### ISSUE TITLE
Upravit popisky na dílech rotoru

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#74]
Popisky obsahující číslo týdne a nějaké označení je vhodné mít označené z horní strany. Zjednodušuje to sestavování a omezuje možnou chybu špatného složení rotoru. 

Špatně je to u 

- [x]  trhací placky (která pak lze namontovat obráceně)
- [x] rotorových listů (kde to není tak velký problém)

**Comment by roman-dvorak** [comment]
@kaklik  tohle je hotové, ne?

**Comment by kaklik** [comment]
Ano, je to otočený, ale ještě nebyly vyrobené žádné listy s touhle novou ůpravou, proto je to jen jako resoved a není to zavřený.

**Comment by kaklik** [comment]
Rotor s otočenými popisky již byl vytištěn.
