### ISSUE TITLE
Zmenšení pevnosti na lom rotorových trhacích placek

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#75]
Aktuální verze rotorových placek je velmi pevná na lom. Díky tomu se ničí velké množství listů.

@kaklik navrhl, aby zářez byl trojúhelníkový. Aby na vnítřní straně byl ostrý úhel. 

Trhací placky mají být první deformační zóna. Druhou má být trhací rotorová hlava: #69

**Comment by roman-dvorak** [comment]
S tímto issue je efektivní vyřešit i #74 u dílu trhací placky

**Comment by kaklik** [comment]
Tak jsem otočil smysl středových děr, čímž se popisky myslím dostaly na vrchní stranu ve složeném rotoru. 

![image](https://user-images.githubusercontent.com/1194177/100257866-b1139980-2f46-11eb-8e53-8616f057bf1d.png)

A taktéž trhací otvory vyměnil za 4hrany. Zde trochu váhám, jestli na rotoru neexistuje nějaká asymetrie sil při nárazu listu, která by se dala využít k lepšímu utržení listu.  Přijde mi ale, že když se jeden list dotkne země, tak síla která je vyvozená druhým stále rotujícím listem, na jeho závěs je symetrická.

**Comment by roman-dvorak** [comment]
Zřejmě je zeslabení nedostatečné.

Nepomohlo by trhací otvory přesunout do flapovací spáry? Protože v tomto místě je placka stažená docela velkou silou, z obou stran, rotorovým listem a spodní podložkou.

**Comment by kaklik** [comment]
Ve flapovací spáře se ale místo předpokládaného roztržení bude cyklicky namáhat. Takže zde bude postupně vznikat prasklina i bez namáhání listů silami, které mají vést k utržení. 

Navrhoval bych snížit počet perimetrů trhací podložky. Zdá se že sílu přenáší v místě roztržení hlavně perimetry.

**Comment by kaklik** [comment]
Na základě posledních testů mi přijde, že toto issue je již irelevantní, neboť k utržení listů po dopadu docházelo i bez jejich znatelného poškození.
