### ISSUE TITLE
Zlepšená konstrukce pylonu a rotorové hlavy

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TF-G2#82]
- [x] Spodní rámeček 888_1007
 - [x] Spodní část držáku silentbloků 888_1008
 - [x] Vybrat + otestovat správné silentbloky
 - [x] Horní část držáku silentbloků
 - [x] Implementace Airspeed #16 
 - [x] Umístění serv #70 
 - [x] Rotorová hlava
 - [x]  #69

<hr> 

Protože doposud nedošlo k výrobě vírníku v podobě frézovaných (nebo laserem pálených) dílů, tak bych odstoupil od tohoto způsobu výroby. Trochu bych se inspiroval tyčovým pylonem na TF-G1. 

Uprostřed kostry vírníku by byl rámeček, který bude zpevňovat trup a bude pevným základem pylonu. V něm by byly 4 uhlíkové tyčky průměru 6 nebo 7 mm (jako jsou aktuálně na platformě). Ty povedou do druhého rámečku. V rámečcích budou zalepeny. Skládání bude probíhat tak, že se tyčky prostrčí ze spodní strany do horního rámečku. Tím bude skládání snazší než u pylonu TF-G1. 

Do horního rámečku budou zašroubovány 4 silentbloky, které budou fungovat jako odpružení/odvibrování pylonu. Ovládací prvky budou z důvodu tuhosti řízení v horní části rotorové hlavy. 

Horní část ještě nemám přesně promyšlenou. Ale mělo by to vypadat tak, že bude co nejnižší a nejkompaktnější. Stále se počítá s uspořádáním serv na boku. Protože to snižuje podélnou plochu pylonu a zároveň tuhost řízení. V této části bude také airspeed senzor, který může být nyní širší tak, jak potřebujeme (@JanKott #16).  

Také jsem přemýšlel o rotorové hlavě založené na kulovém čepu. Ale s tím si nejsem jistý. 

Další otázka je implementace trhacího pylonu. Nabízí se několik řešení. Nejvíce se mi líbí, že by se vytrhly silentbloky v nějakém definovaném - oslabeném místě. (I tak se rotor má prioritně  trhat v listech #75 popř. domku ložisek rotoru #69 :smile: ) 

Očekával bych, že by se těmito změnami zvětšila pevnost celé konstrukce.

**Comment by kaklik** [comment]
Tak mám teď po montáži nových zařízení na střechu měřícího auta a zároveň z průběhu testů tomu několik domnívám se zásadních poznatků. 

1. Vypadá to, že aerodynamický odpor na střeše auta zvětšují zejména kabely, tedy tenké objekty v malém kruhovém průřezu zasahující do proudu vzduchu. Je to sice poměrně neexaktní měření, ale změna je po přidání kabelů myslím i slyšitelná. 
2. Zdá se že realizace vícetyčkového pylonu s tyčkami malého průřezu není dobře realizovatelná. Protože je problém s rozkladem sil do větší plochy modelu z tenké uhlíkové tyčky. Tento problém by zřejmě bylo možné vyřešit, ale už i dosud vynaložené úsilí je nemalé.  
3. Kvůli budoucí změně konstrukce ocasní plochy by bylo výhodné, kdyby existovala středová tyčka pod pylonem na kterou by bylo možné uchytit otočnou směrovku umístěnou pod rotorem. Tato úvaha vede k redukci počtu stojin v pylonu ze čtyř na tři. 

Kvůli výše zmíněným bodům bych proto navrhoval konstrukci pylonu změnit na jednotrubkovou verzi. :) Vím že podobné řešení měl i původní TF-G1. V jehož případě vznikal problém zejména s použitím prerotátoru a s pevností spoje mezi vertikální stojinou a podélnou osou trupu. 
Domnívám se, že u malé verze TF-G2 by tyto potíže vznikat nemusely. Neboť nemá prerotátor a spoj mezi vertikálním pylonem a trupem je stejně realizován silentbloky, což je řešení, které by myslím bylo vhodné zachovat. 

Potřebná změna by tak byla pouze v úpravě spodního montážního rámečku pro pylon tak, aby obsahoval kříž do jehož středu by bylo možné vertikální pylon uchytit. Nahoře u rotorové hlavy by trubka mohla být vetknuta do nejtlustšího místa TFSLOT. 

Toto nové řešení by mohlo mít výhodu i ve snazším utěsnění pláště vírníku proti vodě. Neboť na jednoduché vertikální trubce, může být posuvný díl utěsněný o-kroužkem, kterým se přikryje otvor v textilním plášti vírníku. 

Další potenciální výhodou by pak mohla být možnost vedení kabeláže uvnitř trubky. To by mohlo být významné zejména v situaci, kdy by se použila trubka o průměru 13mm, která by měla být dostatečná pro prostrčení prodlužováku servokabelu.

**Comment by kaklik** [comment]
K vedení kabeláže z pylonu existuje ještě alternativní možnost na trubku vytvořit nacvakávací 3D tištěný kryt s tvarem NACA profilu, kterým budou kabely svedeny do prostoru trupu. 

Takové řešení by bylo užitečné zejména v případě, že bychom na pylon použili aktuální trubku s průměrem 10mm používanou na ocas.  Tenčí trubka pak může být pro zjednodušení konstrukce zatím upevněna šroubem prošroubovaným středem trubky.

**Comment by kaklik** [comment]
@roman-dvorak  udělal úpravu konstrukce pylonu rotorové hlavy, která pravděpodobně všechny zmíněné potíže řeší. 

![215679114_1043038936230920_80529097423265850_n](https://user-images.githubusercontent.com/1194177/125866308-d030e3a5-2b51-4963-a1b4-b8c252f3ab06.jpg)


![211379876_221548773167829_5182285777967061688_n](https://user-images.githubusercontent.com/1194177/125866320-1f3b6cf4-a639-4efc-8444-7107e2a0538f.jpg)

![209975819_4367742979944518_2815165295766180974_n](https://user-images.githubusercontent.com/1194177/125866342-3a8bfab4-5654-4998-99f5-a020532e7ca5.jpg)

Hlavním zádrhelem tak je nedokončená realizace vyměnitelného dílu lámací rotorové hlavy #69

**Comment by kaklik** [comment]
S novou konstrukcí pylonu bylo již provedeno několik letů bez zjevných nedostatků.
