### ISSUE TITLE
Vypadávaní servokonektorů z autopilota

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#84]
U autopilota CUAV V5 nano je poměrně snadné, aby došlo k vypadnutí servokonektorů. Na rozdíl od CUAV V5+ zafixování konektorů nelze jednoduše řešit použitím stahovacího pásku přes přívodní kabely. 

Řešením možná je vytvoření 3D tištěného krytu, který by bránil nechtěnému vypadnutí konektorů. Zároveň by mohl zajišťovat, že konektory budou vždy zasunuty do správných pozic.

**Comment by roman-dvorak** [comment]
Nechápu, proč to nejde udělat jako u CUAV V5+? Myslím, že to lze udělat úplně stejně velmi snadno. 

Rozdíl, mezi CUAV V5+ a Nano v tomto je pouze směr hřebínku. Konektor je stejný.

**Comment by kaklik** [comment]
ok, můžeme to zkusit. Určitě to bude rychlejší, než kreslit model fixačního dílu. 

Rozdíl já vnímám v tom, že vertikálně vyvedený hřebínek nad sebou nemá plochu ke které by se všechny vodiče daly přitáhnout.

**Comment by roman-dvorak** [comment]
Teď předpokládám, že všechny dráty vedoucí do pylonu budou přitažené ke
spodnímu rámečku pylonu. V ideálním případě bude nad tímto místem spojka
konektorů.


Dne pá 25. 12. 2020 22:24 uživatel Jakub Kákona <notifications@github.com>
napsal:

**Comment by roman-dvorak** [comment]
Prozatím vyřešeno přeorganizováním drátů; další úpravy budou v rámci úpravy pylonu.
