### ISSUE TITLE
Uchycení podvozkových nohou

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#86]
[Aktuální sestava](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/CAD/src/assembly/full_assembly.scad) v místě, kde mají být uchycené podvozkové nohy vypadá takto: 

![image](https://user-images.githubusercontent.com/1194177/105776881-af2b7e00-5f69-11eb-903b-cf597f4ba3f0.png)

Protože podvozková noha je část, která se bude pravděpodobně i v budoucnu poměrně často měnit, tak je zřejmě vhodné její uchycení konstruovat tak, aby byla snadno vyměnitelná. 

### Přechodový díl pro uchycení podvozkové nohy

Z toho mi vyplývá že by neměla být uchycena na pouzdro akumulátorů jak bylo původně v plánu, ale v místě kolmého spoje bočnice a spodní podložky.  Protože bočnice i podložka v tomto místě snadno praskají, tak je nutné oba díly vyztužit.
Důvody proč podvozek nemít uchycený na pouzdro akumulátorů jsou následující:

- Při sundání pouzdra akumulátoru by nebylo na co vírník položit
- Všechny síly z podvozku přenášely přes pouzdro akumulátoru, což může zbytečné vést k jeho zbytečnému poškození
- K udržení rozchodu by muselo být rozšíření provedeno délkou podvozkové nohy, což je nevýhodné, protože tenká podvozková noha je už nyní náchylná na ukroucení a její horizontální prodloužení by tuto situaci jen zhoršilo. 

Toho lze dosáhnout konstrukcí nového dílu, který bude přišroubován k bočnicím, tak že vyztuží spoj bočnice a podložky.  K tomuto dílu bude teprve šroubována podvozková noha. 

Benefity tohoto řešení jsou: 
-  Není nutné, aby podvozková noha měla rastr děr přesně shodný s rastrem bočnic
-  Fakt že montážní adaptér podvozkové nohy bude šroubován k bočnici lze využít k zajištění matice pro podvozkovou nohu proti bočnici tak, že není možné, aby po odšroubování podvozkové nohy matice vypadla
-  Adaptér může na straně podvozkové nohy končit rovnou plochu, není tak nutné, aby podvozková noha měla levou nebo pravou variantu 
- Tvarem adaptéru lze jednoznačně definovat umístění podvozkové nohy na bočnici a nemůže tak dojít k montážnímu omylu.

**Comment by kaklik** [comment]
Uchycení podvozkových nohou bude zřejmě potřeba nějak upravit i v místě připojení k trupu. Neboť je to aktuálně nejcitlivější část podvozkové nohy, která je náchylná na poškození. 

![151697486_451411505907124_5365662414522548894_n](https://user-images.githubusercontent.com/1194177/108273871-7485c180-7174-11eb-9fe3-91be00c777fe.jpg)

![151348551_867904543969627_8217569189202809832_n](https://user-images.githubusercontent.com/1194177/108273885-78b1df00-7174-11eb-9e39-0a580aa90308.jpg)

![151544398_258298902532447_793557808474739759_n](https://user-images.githubusercontent.com/1194177/108273896-7c456600-7174-11eb-9503-6e56b24269b1.jpg)

**Comment by kaklik** [comment]
K ukrucujícím se podvozkovým nohám mám následující návrh jak to vyřešit: 

Stačí ty odlehčovací trojuhelníky  na začátku udělat menší a začít je zmenšovat až třeba v 1/3 délky té nohy. Tím vznikne u kořene té nohy délka, kde se bude postupně ztenčovat ten materiál, protože noha se bude zužovat ale trojúhelníky budou nejdřív chvíli stejný (menší než jsou teď).

Respektive stačí, aby zmenšování trojúhelníků mělo trochu jiný spád, než je zužování nohy. Tím vznikne u kořene nohy více materiálu, který bude schopen přenášet zvýšené zatížení vznikající na páce nohy. 

Aktuální řešení totiž obsahuje problém, že zatížení podvozkové nohy směrem ke kořenu roste, ale neroste průřez materiálu, přes který se síla může přenášet.

**Comment by kaklik** [comment]
Aktuální úprava zřejmě řeší potíž s ukrucováním nohy popsané v komentáři výše. 

![image](https://user-images.githubusercontent.com/1194177/116914364-ef765880-ac4a-11eb-8f6d-36150079f7e6.png)

Zbývá tak návrh nového dílu, který umožní napojení na trup.

**Comment by kaklik** [comment]
> Ještě by mi přišlo lepší pro tisk, kdyby ta základna trojúhelníků byla v rovině se zůžením nohy.

Ano, souhlasím, na to je separátní issue, které zatím nikdo neřeší https://github.com/ThunderFly-aerospace/TF-G2/issues/98

> 
> Ještě mě napadlo, co zkusit nějaký takovýhle nástroj na analýzu problému lámání nohou: https://youtu.be/7pKvMlo5aMw
> Já si totiž myslím, že by tam uvnitř měla být přenosová výstuha.


Nemyslím si, že je nyní přímo problém v té konstrukci podvozkové nohy. Ale takovýhle nástroj by mohl být užitečný i pro jiné díly. Problémem u 3D tisku je ale to, že ten tištěný model není homogenní, takže to nelze počítat s izotropními tenzory.  Možná to ale jde nějak vyřešit, nezkoušeli jsme to. 

V případě podvozkových nohou je ale nyní myslím problém hlavně v tom vůbec mít nakreslené všechny díly. Druhý problém je pak jejich správné dimenzování, ale to už lze udělat metodou pokus-omyl.

**Comment by kaklik** [comment]
@roman-dvorak udělal provizorní úpravu pro montáž podvozkové nohy, která ale moc nezohledňuje zdejší původní plán.

![image](https://user-images.githubusercontent.com/1194177/118496089-1725f000-b724-11eb-8139-60bd810a2209.png)

Nicméně zřejmě umožní dočasnou montáž aktuálně navržených podvozkových nohou.

**Comment by kaklik** [comment]
Řešení, které bych navrhoval si představuji nějak takhle: 

![image](https://user-images.githubusercontent.com/1194177/118658097-6172a400-b7ec-11eb-9e0b-de26c1a9bddf.png)


Z boku by vypadalo přibližně takto: 

![image](https://user-images.githubusercontent.com/1194177/118658191-72bbb080-b7ec-11eb-9ff3-a60b4ee6cf52.png)


Jde o to, že šrouby nohy nebudou pokračovat skrz bočnici, ale budou posunuté oproti původnímu rastru na bočnici.  Všechny šrouby přitom mohou být klidně utopené, neboť adaptér (888_2004) může být dostatečně tlustý na to aby to bylo možné.

**Comment by kittlerm** [comment]
Problem trochu je, podstavec pro nohu přesahuje tu rozteč bočnice, takže buď jsou šrouby pro nohy ve vzduchu nahoře nebo dole:
![image](https://user-images.githubusercontent.com/74110453/118733211-6571e680-b82b-11eb-841b-87762422911d.png)
![image](https://user-images.githubusercontent.com/74110453/118733250-73276c00-b82b-11eb-8961-eabb04817e11.png)

**Comment by kittlerm** [comment]
Tak to mam asi hotove (ackoli je to cunada, kopiruje to celou 1003), akorat vymyslet umisteni:
![image](https://user-images.githubusercontent.com/74110453/118738005-8f300b00-b835-11eb-9c6d-849a35e6e777.png)
![image](https://user-images.githubusercontent.com/74110453/118738131-d918f100-b835-11eb-9e9a-8559c1739fdb.png)

**Comment by roman-dvorak** [comment]
Aby to šlo takto použít, tak tam bude potřeba přidat nějaké tolerance okolo té drážky na  bočnice.

**Comment by kittlerm** [comment]
> Aby to šlo takto použít, tak tam bude potřeba přidat nějaké tolerance okolo té drážky na bočnice.

jj taky jsem si rikal, i na ty ostatni diry na kryt, dnes to zkusmo vytisknu a kouknu na to.

**Comment by kittlerm** [comment]
Mám ale větší problém, že se neobjevil nový gcode v gcodes repu https://github.com/ThunderFly-aerospace/gcodes/blob/TF-G2/refs/heads/mini/edee/gcode/TF-G2_printplate_888_2004.gcode

**Comment by kittlerm** [comment]
> Aby to šlo takto použít, tak tam bude potřeba přidat nějaké tolerance okolo té drážky na bočnice.

Nakonec ten okraj zvětšovat ani není třeba:
![image](https://user-images.githubusercontent.com/74110453/118798925-b61a2b80-b88d-11eb-8e29-b8e44a4371b2.png)

Ale už to mam připravené, jen musím ještě doladit výšku, protože M3x12 je málo a M3x14 je moc a nevejde se, následně dochází k odtažení od bočnice, protože šroub nemá kam pokračovat, proto bych navrhoval, aby ty díry seděli na těch dírách s bočnicemi, ale byli použity jen některé. Co @kaklik  na to?

**Comment by kittlerm** [comment]
Ano, už to mám odzkoušené a připravené, včetně možnosti nechat matku více "zapustit". Ale montáž není moc příjemná, chtělo by to přepracovat tu úchytku nohy

**Comment by kittlerm** [comment]
Podobně jako je u ostatních dílů chybí zaslepení převisů nad šrouby ( např v https://github.com/ThunderFly-aerospace/Openscad_stdlib/commit/dabd1c7fbdc589b41f5c05d1f52508fff8bbd241#r51066808 )

**Comment by kittlerm** [comment]
> > Ano, už to mám odzkoušené a připravené, včetně možnosti nechat matku více "zapustit". Ale montáž není moc příjemná, chtělo by to přepracovat tu úchytku nohy
> 
> Nestačilo by na těch úchytech nohy jen dát ty díry na šrouby dál od sebe? Aby tam bylo více místa na šroubování..
> Jiný nápad moc nemám, protože ty podvozkové nohy nejde snadno rozšířit, aby šrouby šly dát více doboku.

Jo říkal jsem si, že by pomohlo rozšířit rozteč děr

**Comment by kittlerm** [comment]
@roman-dvorak @kakl : můžete mi prosím ukázat, jak správně přichytit kolečko? Objímka, ložisko nebo prostě na hulváta šroub?

**Comment by roman-dvorak** [comment]
No, vzhledem k tomu, že se to kolečko reálně moc neotáčí, tak nebyl problém ho připvňovat šrubem se samojistnou matkou. A podložku z obou stran kola. Zkoušeli jsme to používat s kluzným pouzdrem, ale nebylo to skoro o nic lepší.

**Comment by kaklik** [comment]
@roman-dvorak  Mám za to, že @kittlerm  by měl i ve větvi 4s nahradit tvoje [řešení montáže podvozkové nohy](https://github.com/ThunderFly-aerospace/TF-G2/commit/6e39729c614d194ab27217785f6a86a9e54323e9) s [přidanou kostkou](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/CAD/stl/888_1003.stl),  [novým dílem pro uchycení nohou](https://github.com/ThunderFly-aerospace/TF-G2/blob/8c0f04c6c630bffd450ea20d603912936f5b1760/CAD/stl/888_2004.stl). 
Souhlasíš s tím?

**Comment by roman-dvorak** [comment]
Aktuální implementace je taká strašně monstrózní ;) ... ale dobře. Když to pomůže k vyřešení #109 tak rozhodně.

**Comment by kaklik** [comment]
> Aktuální implementace je taká strašně monstrózní ;) ... ale dobře. Když to pomůže k vyřešení #109 tak rozhodně.

Podle mě to s vyřešením #109 moc nesouvisí, protože je to úprava, která je v nějaké formě potřeba pro všechny varianty vírníku. 
Ale s tím, že je to řešení od @kittlerm  zatím takové neuhlazené souhlasím. To se ale snáz odstraní ve chvíli, kdy to bude používat víc lidí a přijde se na nějaký lepší tvar.

**Comment by kittlerm** [comment]
Můžu zkrátit tuhle část podvozku?
![image](https://user-images.githubusercontent.com/74110453/121873917-66951700-ccf6-11eb-8689-63efb99ee0fa.png)

Přemýšlím, jak ty nohy uchytit do té středové části, a asi bych tam udělal díru jako na šroub, ale zkusil bych to přidělat jen tavným lepidlem:
![image](https://user-images.githubusercontent.com/74110453/121874356-d3101600-ccf6-11eb-97fc-c2508dcfbd59.png)

**Comment by kaklik** [comment]
> Můžu zkrátit tuhle část podvozku?
>

Já moc nerozumím, co to má přinést. Protože i z fotografie mi to přijde, že když ty podvozkové nohy doléhají na sebe, tak jsou akorát o trochu širší než je trup toho vírníku, což je podle mě správně.
 
> Přemýšlím, jak ty nohy uchytit do té středové části, a asi bych tam udělal díru jako na šroub, ale zkusil bych to přidělat jen tavným lepidlem:
> 

Můj odhad je, že by zde mělo stačit jen tištěné poudzro do kterého se zasunou z boku.

**Comment by kittlerm** [comment]
Ty nohy pak kloužou ze strany na stranu, nedrží se na středu. Vyřešit se to dá také lepidlem nebo širokým pouzdrem.

**Comment by kaklik** [comment]
> Ty nohy pak kloužou ze strany na stranu, nedrží se na středu. Vyřešit se to dá také lepidlem nebo širokým pouzdrem.

V tom případě mi přijde jako dobré řešení zalepení nohou tavným lepidlem do širokého pouzdra uprostřed.

**Comment by kaklik** [comment]
Tak k původnímu uchycení podvozku, které je popsané v úvodu issue mám několik nových poznatků.  Aktuální realizace vypadá takto: 

![Uchyceni_podvozku](https://user-images.githubusercontent.com/1194177/126369715-0e389aee-8c28-4e41-af0e-5cae1658b39e.jpg)

![Uchyceni_podvozku_noha](https://user-images.githubusercontent.com/1194177/126369910-11411570-34bb-495c-a78a-57b04cc99fc2.jpg)

Potíž této konstrukce je, že bočnice na kterých drží podvozkové nohy se při zatížení rozjíždí do stran.  @slimonslimon  i @roman-dvorak  tuto záležitost řeší tak, že obě redukce na kterých podvozkové nohy drží propojili závitovou tyčí. 

Podle mě by však bylo lepším řešením  do přední části navrhnout nový díl, který zastane funkci závitové tyče (podrží vzdálenost mezi montážními díly). Další funkce by byla jako aerodynamický kryt a také ochranný kryt konektoru akumulátoru a akumulátoru před nárazem.

**Comment by kaklik** [comment]
Zde je ještě fotka aktuálně používané montáže.

![Uchyceni_podvozku](https://user-images.githubusercontent.com/1194177/127400898-5358b389-7782-4246-86b9-01da0a6d1075.jpg)

**Comment by kaklik** [comment]
Tak tady je ještě doplnění, jak současný způsob uchycení vypadá po havárii

![Uchyceni_podvozku_havarie](https://user-images.githubusercontent.com/1194177/127925917-4ea40164-7161-4f7e-89d8-82b96d52c60d.jpg)

Při dopadu navíc došlo k vytržení vodičů z napájecího konektoru na straně akumulátoru (na fotografii chybí). Tato situace ale zkomplikovala dohledávání, neboť vírník tak byl po havárii bez vysílače telemetrie.

**Comment by kittlerm** [comment]
Co třeba takhle?
![image](https://user-images.githubusercontent.com/74110453/128135369-54baa2aa-ab85-4782-9349-4ebd75ed372d.png)

Přichytávalo by se to těmi spodními šrouby do nohou.

**Comment by roman-dvorak** [comment]
Připadá mi (pouze z obrázku), že to zablokovalo přístup k napajecimu konektoru. A nevím, jestli to nekoliduje s bateriovým pouzdrem na nějaké větší baterky.

**Comment by kaklik** [comment]
Jo, tvarově je to správně. :)

S tím přichytáváním na spodní šrouby od nohou..  Nevim moc jak to myslíš, ale to jsou zrovna šrouby, který se šroubují pěkně blbě, protože se k nim přes tu nohu moc nemůže. 
Tenhle díl by to naopak chtělo mít možnost sundavat nějak relativně snadno. Protože je potřeba připojovat a odpojovat akumulátor vytažením z napájecího konektoru. Jak poznamenal Roman výše. 

Jako nejlepší řešení by mi přišlo, kdyby to šlo na vírník zepředu nasunout po zapojení konektoru. Bez použití šroubováku. 
Myslím že by to šlo udělat tak, že to buď bude mít vhodný tvar s drážkami (které by tak asi musely být i na dílu pro uchycení nohou).  A nebo to tam můžem dočasně přichytávat lepicí páskou (to ale bude mít nevýhodu, že ten díl nenahradí funkci té závitové tyče, která to nyní stahuje.)

**Comment by kittlerm** [comment]
> Připadá mi (pouze z obrázku), že to zablokovalo přístup k napajecimu konektoru. A nevím, jestli to nekoliduje s bateriovým pouzdrem na nějaké větší baterky.

Jo to se musí ošetřit, nevím jestli tam dávat parametr výšky z toho dílu na baterky, aby to lícovalo.



> Jo, tvarově je to správně. :)
> 
> S tím přichytáváním na spodní šrouby od nohou.. Nevim moc jak to myslíš, ale to jsou zrovna šrouby, který se šroubují pěkně blbě, protože se k nim přes tu nohu moc nemůže.
> Tenhle díl by to naopak chtělo mít možnost sundavat nějak relativně snadno. Protože je potřeba připojovat a odpojovat akumulátor vytažením z napájecího konektoru. Jak poznamenal Roman výše.
> 
> Jako nejlepší řešení by mi přišlo, kdyby to šlo na vírník zepředu nasunout po zapojení konektoru. Bez použití šroubováku.
> Myslím že by to šlo udělat tak, že to buď bude mít vhodný tvar s drážkami (které by tak asi musely být i na dílu pro uchycení nohou). A nebo to tam můžem dočasně přichytávat lepicí páskou (to ale bude mít nevýhodu, že ten díl nenahradí funkci té závitové tyče, která to nyní stahuje.)

Ok, zkusím se nad tím zamyslet.

**Comment by kittlerm** [comment]
Tohle by mělo sedět s baterkou a zasouvat se na spodek 2004 (tj. pomocného držáku s podvozkem), ještě udělám nějakou nacvakávací zarážku:
![image](https://user-images.githubusercontent.com/74110453/131049788-44012ab4-674e-4516-a042-e8c5d8e59e74.png)

**Comment by kaklik** [comment]
> Tohle by mělo sedět s baterkou a zasouvat se na spodek 2004 (tj. pomocného držáku s podvozkem), ještě udělám nějakou nacvakávací zarážku:
>

To vypadá dobře!  Myslím že je to celkem řešení problému. Ještě jen musíme asi rozmyslet, jak to tam bude držet.   Paralelní s tím totiž vzniká [tenhle ušitý kryt](https://github.com/ThunderFly-aerospace/TF-G2/issues/39#issuecomment-908228346).  V případě jeho použití by bylo uchycení krycího dílu snadné. Protože na místě by pak držel po zapnutí zipu na textilním krytu. 
Nepříjemné ale je, že pravděpodobně budeme vírník chtít používat i bez takového krytu.

**Comment by kittlerm** [comment]
![image](https://user-images.githubusercontent.com/74110453/131809949-d01912de-2b8f-48f5-87d9-ea85413e7102.png)
Je tam ještě nějaká změna vůči původnímu profilu na větvi mini, takže to musím upravit a otestovat variantu bez kupovaných nohou, tam je úplně jiná rozteč šroubů.

**Comment by kaklik** [comment]
Při posledním testu se ukázalo, že je nepříjemně komplikované vymontovat díl motoru. Protože vyšroubování šroubů, které drží díl motoru brání roh podvozkových nohou

![20210911_144929](https://user-images.githubusercontent.com/1194177/133885025-cc3ffd16-aeb6-44d8-b345-fe318410838e.jpg)
.

**Comment by kittlerm** [comment]
Přidal jsem kryt (2005) do větve s4, neřeší to šrouby. U nich by bylo asi lepší udělat rozteč na podvozku podle dírek v bočnici (2003) a posunout to tak, aby to sedělo na spodní hraně.

**Comment by kittlerm** [comment]
Musím to ještě upravit, je tam malá vůle na lehký posun a hlavně při použití té varianty bez koupeného podvozku je tam málo materiálu, takže to má tendenci vyskočit. Zkusím zapracovat druhou pojížděcí lištu na druhé straně.

**Comment by kittlerm** [comment]
Malinko jsem oříznul rohy - řešení je +/- pišvorc, asi by bylo lepší vytáhnout pozice šroubů z bočnice, ale prozatím takhle:
![image](https://user-images.githubusercontent.com/74110453/191800626-1e90251e-cea7-44af-9570-069c4dfda489.png)

**Comment by kaklik** [comment]
> Malinko jsem oříznul rohy - řešení je +/- pišvorc, asi by bylo lepší vytáhnout pozice šroubů z bočnice, ale prozatím takhle: 

Mě tohle přijde úplně dobrý! :)  Jen to dej všechno do repozitáře tak, aby to příště šlo vytisknout celý a už to nech být. Víc času tomu není třeba věnovat.

**Comment by kittlerm** [comment]
Dávno už to tam je, větev issue_86. Pro tisk jsem si vytáhl amf z artifaktů a oříznul v PrusaSliceru, abych to nemusel tisknout celé, ale jinak je to stejné jako z repositáře. Možná jen to dolní oříznutí není potřeba, to by šlo lehce změnit. Nebo udělat nový díl a mergnout 2002 a 2004? Co na to @roman-dvorak ?

**Comment by slimonslimon** [comment]
2002 a 2004 bych nemegoval - zvětšilo by to samotnou nohu, a ta se musí dost často měnit. díky tomu přechodovému díu je ta výměna poměrně rychla.

já myslím, že ty úpravy můžeš rovnou namergovat do 4s

**Comment by kaklik** [comment]
ok, považuji za vyřešené.
