### ISSUE TITLE
Konstrukce podvozkového kolečka

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#93]
Teď když jsem měnil kolečko na vírníku, tak jsem si všiml, že v místě, kde se kolečko běžně láme jsou špatně připevněny paprsky kola k obrubě. 

![image](https://user-images.githubusercontent.com/1194177/112009914-1d825c00-8b27-11eb-8cdf-c0dd23ec588c.png)

Důvodem pak je že kolečko typicky praskne tímto způsobem: 

![image](https://user-images.githubusercontent.com/1194177/112010365-87026a80-8b27-11eb-91f6-3ccaf6eb10c5.png)

Na některých tiskárnách se může i stát, že se nevytiskne správě: 

![image](https://user-images.githubusercontent.com/1194177/116916756-08343d80-ac4e-11eb-859d-4648259983d4.png)

**Comment by roman-dvorak** [comment]
Nějak jsem tohle issue přehlédl.

Chce si to tedy pokusit pohrát s nastavením slic3r a případně udělat konfiguraci čistě pro kolečko.

Tohle strašně propaguje simplyfi3d, že mají vyřešené.

**Comment by kaklik** [comment]
> 
> Tohle strašně propaguje simplyfi3d, že mají vyřešené.

A jak to mají vyřešené?  
Já si myslím, že je především potřeba, aby ty paprsky byly tištěné jako dvouperimetrové.

**Comment by roman-dvorak** [comment]
![obrazek](https://user-images.githubusercontent.com/5196729/120032520-9952c600-bffa-11eb-977d-933b1840f289.png)

Vypnutí volby "Detect thin wall" způsobilo tuto změnu:
![obrazek](https://user-images.githubusercontent.com/5196729/120032543-a1ab0100-bffa-11eb-8862-760d62c75a0a.png)

**Comment by kaklik** [comment]
> 
> Vypnutí volby "Detect thin wall" způsobilo tuto změnu:
> ![obrazek](https://user-images.githubusercontent.com/5196729/120032543-a1ab0100-bffa-11eb-8862-760d62c75a0a.png)

To mi přijde jako správně.. Teď se ale asi musí zkusit, jestli každý z těch zdvojených perimetrů je dostatečně tlustý proto, aby šel vytisknout..

**Comment by kaklik** [comment]
Na posledních výtiscích kolečka jsou zmíněné potíže opravené. A při posledním testu se kolečko dokonce dříve vyšroubovalo než zničilo.. 

![image](https://user-images.githubusercontent.com/1194177/123163015-8bfdef80-d471-11eb-9840-d954717352c2.png)
