### ISSUE TITLE
Otočení šroubů v rotorovém kloboučku 

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#95]
[Roztáčecí a snímací díl rotoru](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/CAD/stl/888_4008.stl) byl historicky odvozen od [jinak konstruovaného dílu](https://github.com/ThunderFly-aerospace/Auto-G2/blob/master/CAD/stl/111_1004.stl).   V něm byla orientace šroubů zvolena tak, aby bylo možné snadno zkontrolovat jejich utažení. 

S novou konstrukcí dílu však tato orientace přestala dávat smysl a naopak komplikuje složení a výrobu rotoru.  Šrouby v rotorovém kloboučku by tak bylo vhodné otočit, tak aby uvnitř kloboučku byly matice šroubů a nikoliv hlavy šroubů.  Hlavy šroubů jsou nyní ve válcových otvorech na tomto obrázku: 

![image](https://user-images.githubusercontent.com/1194177/116531607-a7200900-a8df-11eb-86df-5f0d2ad12a5a.png)

Důsledkem této změny bude, že všechny šrouby bude možné utáhnout běžným [inbus bitem standardní délky](https://www.boschcentrum.com/bosch-sroubovaci-bit-zvlast-tvrdy-extra-hart-professional-2607001720) a nebude potřeba speciální prodloužený nástroj.

**Comment by kaklik** [comment]
Zde je alternativním řešením vkládání matic  do kapes z boční strany. To by mohlo zmírnit problém vypadávání matic během šroubování, protože z boku je snadné při montáži otvory zakrýt rukou. 

Vhodná konstrukce kapes je použita například v [tomto dílu](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/CAD/stl/888_1018.stl).

**Comment by kaklik** [comment]
Nyní má rotorový klobouček ve větvi [THUNDERMILL01](https://github.com/ThunderFly-aerospace/TF-G2/tree/THUNDERMILL01) kapsy pro matice šroubů

![186498421_4267764183243776_6886709830986274375_n](https://user-images.githubusercontent.com/1194177/118396225-d6a87280-b64e-11eb-975f-18827eef5545.png)

**Comment by roman-dvorak** [comment]
Je tahle úprava nějak mergerovatelná do rolničky v master a 4S větvích?

**Comment by roman-dvorak** [comment]
Minulý týden jsem tuto úpravu zmergerovat do 4s. Obsahovalo to řadu kolizí. Jeden kus byl vytištěný a ještě to není vyzkoušené (ani neletově).

**Comment by kaklik** [comment]
Vírník s upraveným kloboučkem letěl. Potíže nebyly zaznamenány.
