### ISSUE TITLE
Špatná hloubka zapuštění matice v dílu 888_1002

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-G2#97]
Díl 888_1002 má u montážních otvorů nevhodně zvolenou hloubku zapuštění matice.

![image](https://user-images.githubusercontent.com/1194177/116894455-589da200-ac32-11eb-80dc-866c4a32ed4d.png)

V důsledku toho nelze pro montáž dílu použít dva stejně dlouhé šrouby M3x10 nebo delší (v případě montáže podvozku). 

![image](https://user-images.githubusercontent.com/1194177/116894723-aca88680-ac32-11eb-9763-c1e63bdeb8e1.png)

Úprava afektuje verze 4s i verze mini, popřípadě i THUNDERMILL01 úpravu je tak nejvhodnější provést ve větvi 4s, která je base pro další dvě.

**Comment by roman-dvorak** [comment]
Když jsem si teď prohlížel ten díl, tak jsem si uvědomil, že původně měla být trochu zapuštěná hlava předního šroubu. Tak, aby vyčnívaly hlavy obou šroubů stejně.

**Comment by kittlerm** [comment]
Lepsi tohle A]:
![image](https://user-images.githubusercontent.com/74110453/117568749-c07c3e80-b0b1-11eb-80ea-a3db24bdb1a8.png)
nebo tohle B]:
![image](https://user-images.githubusercontent.com/74110453/117568783-e6a1de80-b0b1-11eb-897e-07e51234e9ce.png)
![image](https://user-images.githubusercontent.com/74110453/117568792-f3263700-b0b1-11eb-944a-4f2b1415f680.png)

v kodu je totiz translace bez parametru = warning:
`WARNING: Unable to convert translate(undef) parameter to a vec3 or vec2 of numbers, in file 888_1002.scad, line 141`

**Comment by kittlerm** [comment]
Hotovo, ale meumim to mergnout do větve mini, je tam hodně konfliktů.

**Comment by roman-dvorak** [comment]
Tak to zkus commitnout do nějaké nové větve. A z ní pak vytvoříme pull request a vyřešíme ty konflikty.

**Comment by kittlerm** [comment]
uz to je v 4s

**Comment by kaklik** [comment]
Tak jsem to mergnul do mini..  Nicméně si nejsem jistý, jestli to současné řešení reflektuje připomínku z komentáře https://github.com/ThunderFly-aerospace/TF-G2/issues/97#issuecomment-835508091. V takovém případě bych totiž očekával, že ten šroub více vpředu bude mít v modelu částečně zapuštěnou hlavu.

![image](https://user-images.githubusercontent.com/1194177/117587601-13d8a600-b11f-11eb-91d3-1ff9e46ea624.png)

**Comment by kittlerm** [comment]
Aha, hlava šroubu... ja zapustil matici. Navíc jsem to zkosil, protože mi to přišlo lepší pro tisk, ale pokud to chcete jinak, tak to předělám.

**Comment by kittlerm** [comment]
> Tak, aby vyčnívaly hlavy obou šroubů stejně.

To jde ale zařídit jen tak, že odstraním úplně to přední část nebo tam udělám otvor na hlavu šroubu a bude to jako v u matice mít takovou malou plošku... hloubka zapuštění tedy bude stejná jako tenčí síla stěny v [1003](https://github.com/ThunderFly-aerospace/TF-G2/blob/4s/CAD/stl/888_1003.stl)

![image](https://user-images.githubusercontent.com/74110453/117617149-a5660900-b15b-11eb-8f92-e1fa3d3e0b6a.png)

**Comment by roman-dvorak** [comment]
To zkosení a zapuštění matky je dobré. To určitě nechat. U těch matek je
otázka, jestli je nedat do nějakých kaps. Nebo ten rastr trošku zvětšit.
Jak je to jen do poloviny matky, tak se to strašně blbě dává dohromady.

A zapuštění hlavy šroubu je ještě další úprava. Ano, tak aby to odpovídalo
dílu 1003.

Dne po 10. 5. 2021 8:51 uživatel kittlerm ***@***.***> napsal:

**Comment by kittlerm** [comment]
Hotovo:

![image](https://user-images.githubusercontent.com/74110453/117633450-912b0780-b16d-11eb-8a28-3b4f7dc12d31.png)

**Comment by kittlerm** [comment]
@kaklik prosím ještě o jeden merge.

**Comment by kaklik** [comment]
> @kaklik prosím ještě o jeden merge.

Ok,  mergnuté do mini to je. Nyní to čeká na vyzkoušení. Pak se to může zavřít.

**Comment by kittlerm** [comment]
Za mě to je dobré, akorát se nedá použít M3x6:
![image](https://user-images.githubusercontent.com/74110453/120161043-6d943380-c1e6-11eb-8a61-ae990b20e6db.png)
